In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

Matplotlib is building the font cache; this may take a moment.


In [2]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [3]:
df=pd.read_csv(r"iris.csv")

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df=df.drop('Id',axis=1)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le=LabelEncoder()

In [11]:
df['Species']=le.fit_transform(df['Species'])

In [12]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [16]:
df.corr()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
SepalLengthCm       1.000000     -0.109369       0.871754      0.817954   
SepalWidthCm       -0.109369      1.000000      -0.420516     -0.356544   
PetalLengthCm       0.871754     -0.420516       1.000000      0.962757   
PetalWidthCm        0.817954     -0.356544       0.962757      1.000000   
Species             0.782561     -0.419446       0.949043      0.956464   

                Species  
SepalLengthCm  0.782561  
SepalWidthCm  -0.419446  
PetalLengthCm  0.949043  
PetalWidthCm   0.956464  
Species        1.000000

In [17]:
x=df.drop(columns=['Species'])

In [18]:
y=df['Species']

In [19]:
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [20]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [23]:
x_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
99             5.7           2.8            4.1           1.3
92             5.8           2.6            4.0           1.2
130            7.4           2.8            6.1           1.9
22             4.6           3.6            1.0           0.2
114            5.8           2.8            5.1           2.4
..             ...           ...            ...           ...
25             5.0           3.0            1.6           0.2
45             4.8           3.0            1.4           0.3
89             5.5           2.5            4.0           1.3
63             6.1           2.9            4.7           1.4
71             6.1           2.8            4.0           1.3

[112 rows x 4 columns]

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
logreg=LogisticRegression()

In [26]:
logreg.fit(x_train,y_train)

LogisticRegression()

In [27]:
print("Accuracy:",logreg.score(x_test,y_test)*100)

Accuracy: 89.47368421052632


In [28]:
y_pred=logreg.predict(x_test)

In [29]:
y_pred

array([2, 1, 1, 1, 0, 2, 1, 1, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2, 1, 1,
       2, 2, 2, 2, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 2])

In [31]:
print("confusion matrix:",confusion_matrix(y_test,y_pred))

confusion matrix: [[11  0  0]
 [ 0 10  3]
 [ 0  1 13]]
